/**
 * /go/<slug> — short-link redirector for shareable contexts.
 *
 * Resolution order (first match wins):
 *
 *   1. Affiliate link  — looked up against the affiliateLink Sanity
 *      collection by slug. Applies the program's tracking ID + region
 *      swap (Amazon storefront, Backcountry US ↔ Bergfreunde EU, etc.)
 *      based on x-vercel-ip-country at request time. This is the path
 *      that PDFs hit (the cheat sheet generated by the publish script).
 *
 *   2. Curated short link — defined in CURATED below. Hand-pick the
 *      destination + UTMs for each. Stable URLs you can put on print
 *      that never break.
 *
 *   3. Guide passthrough — any slug that matches a published guide
 *      slug redirects to /guides/<slug> with sensible UTM defaults.
 *
 *   4. Fallback — unknown slugs 302 to the homepage with
 *      utm_campaign=unknown-<slug> so we can detect mistyped / abused
 *      links in analytics.
 *
 * SEO: returns 302 (temporary) so Google doesn't pass /go/* link-juice
 * into the destination — that's intentional, /go/ is for outbound
 * campaign traffic, not a canonical path. Robots.txt should disallow
 * /go/ if we want to be extra-safe.
 */
import { NextResponse } from "next/server";
import { buildUtmUrl } from "../../_lib/utm";
import { client } from "../../../sanity/lib/client";
import {
  resolveRegionalLink,
  withAffiliateParams,
  resolveAmazonRegional,
} from "../../_lib/affiliatePrograms";

const SITE_ORIGIN = process.env.NEXT_PUBLIC_SITE_URL || "https://testedroutes.com";

/**
 * Curated short links. Add entries as campaigns require them.
 * The key is the slug after /go/; the value is the full destination
 * with UTMs already baked in (use buildUtmUrl in code, not here).
 *
 * Convention: keep slugs lowercase, hyphenated, short. Once published,
 * treat them as stable — printed media relies on them not changing.
 */
const CURATED = {
  // "podcast": buildUtmUrl(`${SITE_ORIGIN}/subscribe`, {
  //   source: "shortlink", medium: "podcast", campaign: "podcast-mention-2026",
  // }),
};

/**
 * Look up an affiliateLink by slug. Returns null if not found.
 * Cached per request — Sanity CDN handles the rest.
 */
async function loadAffiliateLink(slug) {
  try {
    return await client.fetch(
      `*[_type == "affiliateLink" && slug.current == $slug][0]{
        _id,
        label,
        "slug": slug.current,
        category,
        url,
        program,
        regions[]{ region, url, program }
      }`,
      { slug },
    );
  } catch {
    return null;
  }
}

async function isPublishedGuide(slug) {
  try {
    const { loadGuideBySlug } = await import("../../_lib/loadGuides");
    const guide = await loadGuideBySlug(slug);
    return !!guide;
  } catch {
    return false;
  }
}

/**
 * Build the final tracked redirect URL for an affiliateLink, applying
 * the right region override + tracking-ID injection.
 */
function buildAffiliateRedirect(link, country) {
  if (!link) return null;
  const resolved = resolveRegionalLink(link, country);
  if (!resolved?.url) return null;

  // Amazon: regional storefront + tag swap from the .com URL the
  // editor pasted as the default. (Authors don't have to manage
  // .co.uk / .de URLs separately.)
  if (resolved.program === "amazon") {
    return resolveAmazonRegional(resolved.url, country);
  }

  // Everything else: append the simple tracking param if the program
  // takes one and the env var is set; pass-through otherwise.
  return withAffiliateParams(resolved.url, resolved.program, country);
}

export async function GET(request, { params }) {
  const { slug: rawSlug } = await params;
  const slug = String(rawSlug || "").toLowerCase().trim();
  if (!slug) {
    return NextResponse.redirect(SITE_ORIGIN, { status: 302 });
  }

  // Vercel injects x-vercel-ip-country. In dev / non-Vercel envs it's
  // missing — falls back to the .com / default region.
  const country = request.headers.get("x-vercel-ip-country") || null;

  // 1. Affiliate link
  const affiliate = await loadAffiliateLink(slug);
  if (affiliate) {
    const target = buildAffiliateRedirect(affiliate, country);
    if (target) {
      return NextResponse.redirect(target, { status: 302 });
    }
  }

  // 2. Curated short link
  if (CURATED[slug]) {
    return NextResponse.redirect(CURATED[slug], { status: 302 });
  }

  // 3. Guide passthrough
  if (await isPublishedGuide(slug)) {
    const target = buildUtmUrl(`${SITE_ORIGIN}/guides/${slug}`, {
      source: "shortlink",
      medium: "referral",
      campaign: slug,
    });
    return NextResponse.redirect(target, { status: 302 });
  }

  // 4. Unknown — fall through to homepage with a tagged "unknown-<slug>"
  // campaign so we can spot mistyped / abused short links in analytics.
  const fallback = buildUtmUrl(SITE_ORIGIN, {
    source: "shortlink",
    medium: "referral",
    campaign: `unknown-${slug.slice(0, 40)}`,
  });
  return NextResponse.redirect(fallback, { status: 302 });
}
